### ISSUE TITLE
database file name returning "Reference not defined error"

### ISSUE THREAD

**Issue by rgerrans** [SenseTecnic/sts-node-red-contrib-litedb#1]
As per the readme, I put the following in my node-red settings.js:
`
litedbFileName: imperihomedb,
`
But it's returning an error of imperihomedb reference not defined when I restart node-red?

Thanks.

**Comment by mblackstock** [comment]
you should put quotes around your filename "imperihomedb" in your settings since it is a string, not a variable. For more flexibility and easier database configuration on your local node red install, you may also want to try the standard sqlite node at  https://flows.nodered.org/node/node-red-node-sqlite

**Comment by rgerrans** [comment]
*facepalm*. Thanks, I should have known better.  I was having problems installing the sqlite node so decided to give yours a try instead. Thanks

**Comment by mblackstock** [comment]
no problem!  The readme was missing quotes.

**Comment by rgerrans** [comment]
Thanks.  I think it's also missing the ending comma if I properly understand the structure of the settings.js file
